# Generated by Django 6.0.7 on 2026-07-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShipmentLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                ("distance", models.FloatField(verbose_name="Расстояние")),
            ],
            options={
                "verbose_name": "Рейс",
                "verbose_name_plural": "Рейсы",
                "ordering": ["-date"],
            },
        ),
    ]
